### ISSUE TITLE
issue w/handler restart ntpd

### ISSUE THREAD

**Issue by erpadmin** [MindPointGroup/RHEL7-STIG#12]
RUNNING HANDLER [RHEL7-STIG : restart ntpd] ************************************
fatal: [sectest]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service ntpd: cannot check nor set state"}
	to retry, use: --limit @/home/user/hardening/roles/stig.retry

PLAY RECAP *********************************************************************
sectest: ok=248  changed=41   unreachable=0    failed=1   

anything i can do to fix this?

**Comment by daswars** [comment]
RHEL/CentOS7 use at default chronyd so you cant write a check for both ntpd and chronyd

**Comment by erpadmin** [comment]
Since it is causing the playbook run to fail, I'll just comment out the restart handler.

**Comment by shepdelacreme** [comment]
This part of the playbook needs to be fleshed out more so that there is a variable defining which time client to use and then separate fix tasks based on if you want `chrony` or `ntpd`. We do this in the RHEL7-CIS and some of the other baseline roles it just hasn't made it to this one yet.

Thanks for the report!

**Comment by samdoran** [comment]
@erpadmin Can you test with this change and see if it fixes your issue?

**Comment by erpadmin** [comment]
I appreciate it.  If still needed Ill try to test this next week.  Thanks.

**Comment by samdoran** [comment]
Yes, please do test and let me know if this works for you.

**Comment by samdoran** [comment]
Fixed in PR #13
