### ISSUE TITLE
Develop Policy for Disabled Tasks

### ISSUE THREAD

**Issue by jamescassell** [MindPointGroup/RHEL7-STIG#120]
Some tasks do not run by default, even though there is an automated remediation available.  When do we disable these?

**Comment by shepdelacreme** [comment]
In the past we had made the decision to disable by default rules that were "risky" to run in some situations. Our primary use case for this is for building AWS golden images. However since there is wider use of this role (especially outside of just AWS image building) it makes sense to disable/enable based on community consensus.

For use cases like AWS or Azure images where certain rules will definitely cause issues I think it would be worth providing a "rule set" with the recommended rules.

**Comment by jamescassell** [comment]
my comment at https://github.com/MindPointGroup/RHEL7-STIG/issues/119#issuecomment-381254864 is related

**Comment by jamescassell** [comment]
I think this is covered under the above-linked comment.
