### ISSUE TITLE
Reasons of commented code at the main.yml task file

### ISSUE THREAD

**Issue by HelioCampos** [MindPointGroup/RHEL7-STIG#57]
Why do we have commented code on the file RHEL7-STIG/tasks/main.yml?
Is this a code that would be runned only at the sysadmin explicity descrition?
If so, couldn't it be moved to another files and just runned if the right tag was passed?
If its not absolutely  necessarily anymore, we could remove from the git now in an well commented git commit and, if necessary, bring it back in the future. Could also create another branch.

Best regards

**Comment by fxfitz** [comment]
I'm +1 on this.

**Comment by shepdelacreme** [comment]
Hmm yes the commented code in `tasks/main.yml` should be removed. It was commented during the cutover from separate audit/patch tasks. Eventually those task files that are included `audit-cat1,2,3.yml` will go away as well (but not yet). 

Instead of the change in your PR #56 it would be better to just remove all that commented code if you want.

**Comment by shepdelacreme** [comment]
Removed commented code in #97
